### ISSUE TITLE
Cannot Import Name 'izip'

### ISSUE THREAD

**Issue by EvanCase54** [simpleai-team/simpleai#66]
By running your example code, I receive the following error.

`Traceback (most recent call last):
  File "C:\Users\Administrator.EvanCasePC\Desktop\test.py", line 1, in <module>
    from simpleai.search import SearchProblem, astar
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\simpleai\search\__init__.py", line 3, in <module>
    from simpleai.search.traditional import breadth_first, depth_first, limited_depth_first, iterative_limited_depth_first, uniform_cost, greedy, astar
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\simpleai\search\traditional.py", line 2, in <module>
    from simpleai.search.utils import FifoList, BoundedPriorityQueue, LifoList
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\simpleai\search\utils.py", line 4, in <module>
    from itertools import izip
ImportError: cannot import name 'izip'`

**Comment by fisadev** [comment]
Hi!
Are you running it using python 3? Currently the project only supports python 2. Python 3 support is on its way, but not ready yet :)
